#! /bin/sh

as86 -o ts.o ts.s
bcc  -c -ansi t.c
ld86 -d -o mtx ts.o t.o mtxlib /usr/lib/bcc/libc.a

sudo mount -o loop FDimage /mnt
sudo cp mtx /mnt/boot
sudo umount /mnt

rm *.o mtx

qemu-system-i386 -fda FDimage -no-fd-bootchk
echo done
